-- use foreign key
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
	state_id INT NOT NULL FOREIGN KEY (id) REFERENCES states(id)
);
